### ISSUE TITLE
Docker-compose is not raising on MacOS

### ISSUE THREAD

**Issue by pablojjimenez** [francescoseccamonte/docker-compose-latex#1]
Runing the provide order: `sudo docker-compose run latex /bin/bash` 

I'm receibing a `PermissionError: Operation not permitted`

**Comment by francescoseccamonte** [comment]
@pablojj1808 I believe you are facing issues with macOS permissions. Maybe this one can help? https://stackoverflow.com/questions/58482352/operation-not-permitted-from-docker-container-logged-as-root

Alternatively, you could try setting it up in such a way it does not require `sudo` privileges: https://docs.docker.com/engine/install/linux-postinstall/

Hope it helps!
